version: '3.8'
services:
  juno:
    container_name: juno
    build:
      context: .
      args:
        FILE_UPLOAD_DIRECTORY: /__uploads__
    ports:
      - '8888:8888'
    environment:
      FILE_UPLOAD_DIRECTORY: /__uploads__
      JWT_REALM: junoland
      JWT_SECRET: sA4]fc4A{222<{Vh)T
      APPLICATION_PORT: 8888
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_ENDPOINT: postgres
      DATABASE_NAME: juno_db
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: juno-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: juno_db
      POSTGRES_PASSWORD: admin
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql